# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Blocks reader settings

Db:
    AzureDataConnString:
        settings-key: Bitcoin-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Bitcoin-LogsConnString
        types:
            - AzureTableStorage

MessageListeningParallelism:
    settings-key: Bitcoin-BlocksReader-MessageListeningParallelism

Network:
    settings-key: Bitcoin-Network
Rpc:
    UserName:
        settings-key: Bitcoin-RpcUserName
    Password:
        settings-key: Bitcoin-RpcPassword
    Host:
        settings-key: Bitcoin-RpcHost

RabbitMq:
    ConnString:
        settings-key: Bitcoin-RabbitConnString	