# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Blocks reader settings

Db:
    AzureDataConnString:
        settings-key: Bitcoin-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Bitcoin-LogsConnString
        types:
            - AzureTableStorage

Network:
    settings-key: Bitcoin-Network

Rpc:
    UserName:
        settings-key: Bitcoin-RpcUserName
    Password:
        settings-key: Bitcoin-RpcPassword
    Host:
        settings-key: Bitcoin-RpcHost

RabbitMq:
    ConnString:
        settings-key: Bitcoin-RabbitConnString	
    Vhost:
        settings-key: Bitcoin-BlocksReader-RabbitVhost
        types:
            - Optional

# 4 by default

    MessageConsumersCount:
        settings-key: Bitcoin-BlocksReader-MessageConsumersCount
        types:
            - Optional

# 8 by default

    MessageProcessorsCount:
        settings-key: Bitcoin-BlocksReader-MessageProcessorsCount
        types:
            - Optional
    
# "00:00:30" by default

    DefaultFirstLevelRetryTimeout:
        settings-key: Bitcoin-BlocksReader-DefaultFirstLevelRetryTimeout
        types:
            - Optional

# "00:10:00" by default

    MaxFirstLevelRetryMessageAge:
        settings-key: Bitcoin-BlocksReader-MaxFirstLevelRetryMessageAge
        types:
            - Optional

# 20 by default

    MaxFirstLevelRetryCount:
        settings-key: Bitcoin-BlocksReader-MaxFirstLevelRetryCount
        types:
            - Optional

# 1000 by default

    FirstLevelRetryQueueCapacity:
        settings-key: Bitcoin-BlocksReader-FirstLevelRetryQueueCapacity
        types:
            - Optional

# 500 by default

    ProcessingQueueCapacity:
        settings-key: Bitcoin-BlocksReader-ProcessingQueueCapacity
        types:
            - Optional

LastIrreversibleBlockMonitoringPeriod:
    settings-key: Bitcoin-BlocksReader-LastIrreversibleBlockMonitoringPeriod
    types:
        - Optional